### ISSUE TITLE
Teacher_dashboard, end_date undefined

### ISSUE THREAD

**Issue by Whippler** [TheSoftwareFactory/DlearnHelsinki#130] opened 2017-11-14 08:40 UTC
Dashboard won't load due to missing value. http://puu.sh/ylHMd/cdf03b03c7.png

Unhandled Rejection (TypeError): Cannot read property 'end_date' of undefined
TeacherDashboard.checkLastSurveyDone
C:/Users/kalle/Documents/GitHub/DlearnHelsinki/src/pages/TeacherDashboard.js:93
  90 |      return s.open === false;
  91 |    });
  92 | 
> 93 |    let lastDate = Date.parse(tempSurveys[0].end_date);
  94 |    let lastSurvey = tempSurveys[0];
  95 | 
  96 |    tempSurveys.forEach(function (s) {
View compiled
(anonymous function)
C:/Users/kalle/Documents/GitHub/DlearnHelsinki/src/pages/TeacherDashboard.js:74
  71 |          surveys = data;
  72 |          console.log(surveys);
  73 |          compo.checkIfSurveyOpen();
> 74 |          compo.checkLastSurveyDone();
  75 | 
  76 |        });
  77 |      } else {
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by matletix** [comment] 2017-11-15 11:08
Duplicate of #119

**Closed by matletix** 2017-11-15 11:08 UTC
